version: '3.0'
services:
  airlines:
    build: 
      context: ./airlines
    container_name: airlines
    ports:
      - "8080:8080"
    networks:
      - povsim
  flights:
    build: 
      context: ./flights
    container_name: flights
    ports:
      - "5001:5001"
    networks:
      - povsim
  frontend:
    build: 
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - povsim
  alloy:
    image: grafana/alloy:latest
    container_name: alloy
    ports:
      - "4317:4317"
      - "4040:4040"
    restart: unless-stopped
    volumes:
      - ./alloy/config.alloy:/etc/alloy/config.alloy:ro
    networks:
      - povsim
    command:  
      - "run"  
      - "--server.http.listen-addr=0.0.0.0:12345"  
      - "--stability.level=public-preview"  
      - "/etc/alloy/config.alloy"  

networks:
  povsim:
    driver: bridge