apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pov-sim.fullname" . }}-config
  labels:
    {{- include "pov-sim.labels" . | nindent 4 }}
data:
  environment: {{ .Values.environment | quote }}
  otel-collector-endpoint: "http://{{ .Values.monitoring.alloyService }}.{{ .Values.monitoring.namespace }}.svc.cluster.local:4317"
  pyroscope-endpoint: "http://{{ .Values.monitoring.alloyService }}.{{ .Values.monitoring.namespace }}.svc.cluster.local:4040"
  faro-endpoint: "http://{{ .Values.monitoring.alloyService }}.{{ .Values.monitoring.namespace }}.svc.cluster.local:12347/collect"