apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pov-sim.fullname" . }}-flights
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "pov-sim.labels" . | nindent 4 }}
    app.kubernetes.io/component: flights
spec:
  replicas: {{ .Values.flights.replicas }}
  selector:
    matchLabels:
      {{- include "pov-sim.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: flights
  template:
    metadata:
      annotations:
        profiles.grafana.com/cpu.ebpf.enabled: "true"
        profiles.grafana.com/memory.ebpf.enabled: "true"
        profiles.grafana.com/pprof.enabled: "true"
      labels:
        {{- include "pov-sim.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: flights
    spec:
      containers:
      - name: flights
        image: "{{ .Values.flights.image.repository }}:{{ .Values.flights.image.tag }}"
        imagePullPolicy: {{ .Values.flights.image.pullPolicy }}
        ports:
        - name: http
          containerPort: 5001
          protocol: TCP
        env:
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: "service.name=flights,service.namespace={{ .Values.namespace }},deployment.environment={{ .Values.environment }},service.version={{ .Values.flights.image.tag}},hodeveloper.name=DavidBrush,developer.title=ObservabilityArchitect"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://{{ .Values.monitoring.alloyService }}.{{ .Values.monitoring.namespace }}.svc.cluster.local:4318"
        - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
          value: "http://{{ .Values.monitoring.alloyService }}.{{ .Values.monitoring.namespace }}.svc.cluster.local:4318/v1/traces"
        - name: OTEL_EXPORTER_OTLP_METRICS_ENDPOINT
          value: "http://{{ .Values.monitoring.alloyService }}.{{ .Values.monitoring.namespace }}.svc.cluster.local:4318/v1/metrics"
        - name: OTEL_EXPORTER_OTLP_PROTOCOL
          value: "http/protobuf"
        - name: OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED
          value: "true"
        - name: OTEL_LOGS_EXPORTER
          value: "console,otlp"
        - name: OTEL_METRICS_EXPORTER
          value: "otlp"
        - name: PYROSCOPE_APPLICATION_NAME
          value: "flights"
        - name: PYROSCOPE_SERVER_ADDRESS
          value: "http://{{ .Values.monitoring.alloyService }}.{{ .Values.monitoring.namespace }}.svc.cluster.local:4040"
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 10
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 15
          periodSeconds: 5
        resources:
          {{- toYaml .Values.flights.resources | nindent 10 }}