apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pov-sim.fullname" . }}-frontend
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "pov-sim.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      {{- include "pov-sim.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: frontend
  template:
    metadata:
      labels:
        {{- include "pov-sim.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: frontend
    spec:
      containers:
      - name: frontend
        image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
        imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        env:
        - name: REACT_APP_AIRLINES_API_URL
          value: "http://{{ include "pov-sim.fullname" . }}-airlines.{{ .Values.namespace }}.svc.cluster.local:8080"
        - name: REACT_APP_FLIGHTS_API_URL
          value: "http://{{ include "pov-sim.fullname" . }}-flights.{{ .Values.namespace }}.svc.cluster.local:5001"
        - name: REACT_APP_FARO_URL
          valueFrom:
            secretKeyRef:
              name: grafana-cloud-faro
              key: token
        - name: REACT_APP_VERSION
          value: {{ .Values.frontend.image.tag | quote}}
        - name: REACT_APP_ENVIRONMENT
          value: {{ .Values.environment | quote}}
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 10
          periodSeconds: 5
        resources:
          {{- toYaml .Values.frontend.resources | nindent 10 }}